<script lang="ts" module>
	import { defineMeta } from '@storybook/addon-svelte-csf';
	import AudioPlayer from './AudioPlayer.svelte';
	import { transcriber } from '$lib/transcriber.svelte';

	const { Story } = defineMeta({
		title: 'Components/AudioPlayer',
		component: AudioPlayer,
		tags: ['autodocs'],
		args: {
			recorder: {
				audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/c8/Example.ogg',
				audioBlob: new Blob()
			}
		}
	});

	export { Story };
</script>

<Story name="Default" />

<Story
	name="Transcribing"
	play={async () => {
		transcriber.status = 'transcribing';
	}}
>
	{#snippet children(args: any)}
		<div
			style="background: #080808; padding: 5rem; display: flex; justify-content: center; align-items: center; min-height: 400px; border-radius: 20px;"
		>
			<div style="width: 100%; max-width: 600px;">
				<AudioPlayer {...args} />
			</div>
		</div>
	{/snippet}
</Story>

<Story
	name="With Transcript"
	play={async () => {
		transcriber.transcript =
			'This is a sample transcript generated by the Web Speech API. It can be reviewed and edited directly within this expanded audio player capsule before you post your voice note to Mastodon.';
	}}
>
	{#snippet children(args: any)}
		<div
			style="background: #080808; padding: 5rem; display: flex; justify-content: center; align-items: center; min-height: 400px; border-radius: 20px;"
		>
			<div style="width: 100%; max-width: 600px;">
				<AudioPlayer {...args} />
			</div>
		</div>
	{/snippet}
</Story>
